PHASE 3 — SQL BUSINESS ANALYSIS

In [1]:
import pandas as pd
import sqlite3

In [2]:
df = pd.read_csv("../data/cleaned/superstore_final.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Quarter,Shipping Days,Profit Margin
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2023,January,1,4,33.75
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,2023,January,1,4,-155.00
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Avery 508,11.784,3,0.2,4.2717,2023,January,1,4,36.25
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,2023,January,1,4,-23.75
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2023,January,1,7,25.00

CREATE SQL DATABASE (IN MEMORY)

In [3]:
conn = sqlite3.connect(":memory:")

LOAD DATA INTO SQL TABLE

In [4]:
df.to_sql("sales", conn, index=False, if_exists="replace")

10194

In [5]:
pd.read_sql("SELECT * FROM sales LIMIT 5", conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Quarter,Shipping Days,Profit Margin
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2023,January,1,4,33.75
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,2023,January,1,4,-155.00
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Avery 508,11.784,3,0.2,4.2717,2023,January,1,4,36.25
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,2023,January,1,4,-23.75
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2023,January,1,7,25.00

SQL QUERIES

QUERY 1 — Total Sales & Profit

In [6]:
pd.read_sql("""
SELECT 
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM sales
""", conn)

    Total_Sales  Total_Profit
0  2.326534e+06   292296.8146

QUERY 2 — Sales by Category

In [7]:
pd.read_sql("""
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC
""", conn)

          Category  Total_Sales
0       Technology  839893.2790
1        Furniture  754747.7613
2  Office Supplies  731893.3140

QUERY 3 — Profit by Category

In [8]:
pd.read_sql("""
SELECT Category,
       SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category
ORDER BY Total_Profit DESC
""", conn)

          Category  Total_Profit
0       Technology   146543.3756
1  Office Supplies   126023.4434
2        Furniture    19729.9956

QUERY 4 — Sales by Region

In [9]:
pd.read_sql("""
SELECT Region,
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC
""", conn)

    Region  Total_Sales
0     West  739813.6085
1     East  691828.1680
2  Central  503170.6728
3    South  391721.9050

QUERY 5 — Top Customers

In [10]:
pd.read_sql("""
SELECT "Customer Name",
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Customer Name"
ORDER BY Total_Sales DESC
LIMIT 10
""", conn)

        Customer Name  Total_Sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

QUERY 6 — Top Products

In [11]:
pd.read_sql("""
SELECT "Product Name",
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 10
""", conn)

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479
5   GBC Ibimaster 500 Manual ProClick Binding System    19024.500
6               Hewlett Packard LaserJet 3310 Copier    18839.686
7  HP Designjet T520 Inkjet Large Format Printer ...    18374.895
8          GBC DocuBind P400 Electric Binding System    17965.068
9        High Speed Automatic Electric Letter Opener    17030.312

QUERY 7 — Loss Making Products

In [12]:
pd.read_sql("""
SELECT "Product Name",
       SUM(Profit) AS Total_Profit
FROM sales
GROUP BY "Product Name"
HAVING Total_Profit < 0
ORDER BY Total_Profit ASC
""", conn)

                                          Product Name  Total_Profit
0            Cubify CubeX 3D Printer Double Head Print -8.879970e+03
1            Lexmark MX611dhe Monochrome Laser Printer -4.589973e+03
2            Cubify CubeX 3D Printer Triple Head Print -3.839990e+03
3    Chromcraft Bull-Nose Wood Oval Conference Tabl... -2.876116e+03
4    Bush Advantage Collection Racetrack Conference... -1.934398e+03
..                                                 ...           ...
297                 Brites Rubber Bands, 1 1/2 oz. Box -5.148000e-01
298                                   Rubber Band Ball -2.992000e-01
299  Acco PRESSTEX Data Binder with Storage Hooks, ... -1.614000e-01
300                           Global Super Steno Chair -1.953993e-13
301                     Premier Electric Letter Opener -1.918465e-13

[302 rows x 2 columns]

QUERY 8 — Monthly Sales Trend

In [13]:
pd.read_sql("""
SELECT "Order Month",
       SUM(Sales) AS Monthly_Sales
FROM sales
GROUP BY "Order Month"
""", conn)

   Order Month  Monthly_Sales
0        April    138098.7486
1       August    161821.9150
2     December    330218.1755
3     February     59751.2514
4      January     96069.5156
5         July    149001.7130
6         June    153459.9973
7        March    210672.0868
8          May    158765.0337
9     November    352665.9910
10     October    207126.2567
11   September    308883.6697

QUERY 9 — Sales by Segment

In [14]:
pd.read_sql("""
SELECT Segment,
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Segment
""", conn)

       Segment   Total_Sales
0     Consumer  1.170660e+06
1    Corporate  7.158061e+05
2  Home Office  4.400684e+05

QUERY 10 — Shipping Performance

In [15]:
pd.read_sql("""
SELECT "Ship Mode",
       AVG("Shipping Days") AS Avg_Shipping_Days
FROM sales
GROUP BY "Ship Mode"
""", conn)

        Ship Mode  Avg_Shipping_Days
0     First Class           2.182171
1        Same Day           0.043876
2    Second Class           3.237999
3  Standard Class           4.995425

QUERY 11 — Average Order Value

In [16]:
pd.read_sql("""
SELECT AVG(Sales) AS Avg_Order_Value
FROM sales
""", conn)

   Avg_Order_Value
0       228.225854

QUERY 12 — High Discount Impact

In [17]:
pd.read_sql("""
SELECT Discount,
       AVG(Profit) AS Avg_Profit
FROM sales
GROUP BY Discount
ORDER BY Discount
""", conn)

    Discount  Avg_Profit
0       0.00   66.338799
1       0.10   94.791354
2       0.15   27.288298
3       0.20   24.576350
4       0.30  -45.710633
5       0.32  -88.560656
6       0.40 -111.528378
7       0.45 -226.646464
8       0.50 -310.703456
9       0.60  -41.371458
10      0.70  -95.048521
11      0.80 -101.545745

QUERY 13 — Category + Region Analysis

In [18]:
pd.read_sql("""
SELECT Category, Region,
       SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category, Region
ORDER BY Total_Sales DESC
""", conn)

           Category   Region  Total_Sales
0        Technology     East  267938.0710
1         Furniture     West  260679.7295
2        Technology     West  252766.9880
3   Office Supplies     West  226366.8910
4         Furniture     East  212231.6960
5   Office Supplies     East  211658.4010
6        Technology  Central  170416.3120
7   Office Supplies  Central  168216.7090
8         Furniture  Central  164537.6518
9        Technology    South  148771.9080
10  Office Supplies    South  125651.3130
11        Furniture    South  117298.6840

QUERY 14 — Best Customers by Profit

In [19]:
pd.read_sql("""
SELECT "Customer Name",
       SUM(Profit) AS Total_Profit
FROM sales
GROUP BY "Customer Name"
ORDER BY Total_Profit DESC
LIMIT 10
""", conn)

          Customer Name  Total_Profit
0          Tamara Chand     8981.3239
1          Raymond Buch     6976.0959
2          Sanjit Chand     5757.4119
3          Hunter Lopez     5622.4292
4         Adrian Barton     5444.8055
5          Tom Ashbrook     4703.7883
6  Christopher Martinez     3899.8904
7         Keith Dawkins     3038.6254
8           Andy Reiter     2884.6208
9         Daniel Raglin     2869.0760

QUERY 15 — Profit Margin Analysis

In [20]:
pd.read_sql("""
SELECT Category,
       AVG("Profit Margin") AS Avg_Profit_Margin
FROM sales
GROUP BY Category
""", conn)

          Category  Avg_Profit_Margin
0        Furniture           4.266289
1  Office Supplies          13.999902
2       Technology          15.768028

In [21]:
insights = """
SQL ANALYSIS INSIGHTS:

1. Technology generates highest revenue
2. West region dominates sales
3. Some products are loss-making
4. Shipping delays vary by ship mode
5. Discounts reduce profit in many cases
6. Customer concentration is high (few customers generate most sales)
"""

with open("../exports/sql_insights.txt", "w") as f:
    f.write(insights)

print("SQL Analysis Completed")

SQL Analysis Completed